Disable installmentplaninit call render if payment is disabled
Splitit/Splitit.Plugins.Magento.V2.x pull request #14
Opened 2020-09-23 10:32 UTC by hsour

2020-09-23 18:15 UTC, sixg requested changes
Please act and answer the PR comments.

2020-09-23 18:15 UTC, sixg commented on Splitit/Paymentmethod/Controller/Installmentplaninit/Installmentplaninit.php
> +        if (!$this->helper->getEnableInstallmentPrice()) {
@hsour You should have added the below condition
if ($this->getIsActive() && $this->getEnableInstallmentPrice())
instead of this as getEnableInstallmentPrice only checks if installment price is enabled or not and getIsActive checks if payment method is enabled or not.
And instead of returning a blank response, your code should have been to prevent firing of ajax in the first place.

2020-09-23 18:15 UTC, sixg commented on Splitit/Paymentmethod/Controller/Installmentplaninit/Installmentplaninit.php
> -        $selectedInstallment = "";
Why was this removed ? Some error was shown earlier due to which it was added. Please review and test it with errors and warnings enabled.

2020-09-24 10:43 UTC, hsour commented on Splitit/Paymentmethod/Controller/Installmentplaninit/Installmentplaninit.php
> -        $selectedInstallment = "";
because this variable is overridden immediately after this line. It's not required to set it there.

2020-09-24 10:44 UTC, hsour commented on Splitit/Paymentmethod/Controller/Installmentplaninit/Installmentplaninit.php
> +        if (!$this->helper->getEnableInstallmentPrice()) {
done. I made other changes which will allow us to load js/css files only if the module is active

2020-09-24 18:40 UTC, sixg requested changes
Please review the comments and act accordingly.

2020-09-24 18:40 UTC, sixg commented on Splitit/Paymentmethod/Controller/Installmentplaninit/Installmentplaninit.php
> -        $selectedInstallment = "";
Hi @hsour 
This variable is immediately overridden depending upon the condition and not otherwise.
But it is surely used on line 101.
And if we do not declare the variable then PHP will throw a warning.

2020-09-24 18:40 UTC, sixg commented on Splitit/Paymentmethod/view/frontend/layout/checkout_index_index.xml
> +        </referenceBlock>
@hsour Why this has been added twice ? If it's in default.xml then why was it added here ? As I know default.xml loads on every page.

2020-09-25 10:29 UTC, hsour commented on Splitit/Paymentmethod/Controller/Installmentplaninit/Installmentplaninit.php
> -        $selectedInstallment = "";
It will be overridden or return in else. We will not go to the 101 line in case if it will not be overridden

2020-09-25 10:34 UTC, hsour commented on Splitit/Paymentmethod/view/frontend/layout/checkout_index_index.xml
> +        </referenceBlock>
It has different params. In default.xml we are loading num_of_installment css and js, here we a loads custom files

2020-09-27 17:21 UTC, sixg approved these changes
PR approved since completely tested by @hsour

2020-09-27 17:21 UTC, merged