fix culture name
Splitit/Splitit.Plugins.Magento.V2.x pull request #15
Opened 2020-10-10 14:38 UTC by AlexeyKovalkovvv

2020-10-12 17:28 UTC, sixg reviewed
Need to discuss this with Yan

2020-10-13 06:21 UTC, AlexeyKovalkovvv commented on Splitit/Paymentmethod/Helper/Data.php
> +        }
Maybe yes, but I don't have anything to compare how it was before. Actually we a **SupportedCultures** in a response, but it contains list of cultures and it looks like `["English", "Russian", "Italian", etc]`

2020-10-14 18:06 UTC, sixg requested changes
Please raise this PR into staging instead of master

2020-10-16 15:52 UTC, sixg requested changes
PR to be raised for staging instead of master

2020-10-18 15:22 UTC, closed without merging